#!/bin/bash 
# double.620 (at) 163.com 
# modified from SmartSVN installation. 
# Resolve the location of the ECLIPSE installation. 
# This includes resolving any symlinks. 
PRG=$0 
while [ -h "$PRG" ]; do 
     ls=`ls -ld "$PRG"` 
     link=`expr "$ls" : '^.*-> \(.*\)$' 2>/dev/null` 
     if expr "$link" : '^/' 2> /dev/null >/dev/null; then 
          PRG="$link" 
     else 
          PRG="`dirname "$PRG"`/$link" 
     fi 
done 

ECLIPSE_BIN=`dirname "$PRG"`

# absolutize dir 
oldpwd=`pwd` 
cd "${ECLIPSE_BIN}" 
ECLIPSE_BIN=`pwd` 
cd "${oldpwd}" 

ICON_NAME=icon 
TMP_DIR=`mktemp --directory` 
DESKTOP_FILE=$TMP_DIR/clipse-juno.desktop 
cat < EOF > $DESKTOP_FILE 
[Desktop Entry] 
Version=1.0 
Encoding=UTF-8 
Name=Eclipse Juno 
Keywords=eclipse;juno 
GenericName=Eclipse Juno 
Type=Application 
Categories=Development;RevisionControl 
Terminal=false 
StartupNotify=true 
Exec="$ECLIPSE_BIN/eclipse" %f 
MimeType=x-directory/normal 
Icon=$ICON_NAME.xpm 
X-Ayatana-Desktop-Shortcuts=NewWindow;RepositoryBrowser 

[NewWindow Shortcut Group] 
Name=Open a New Window 
Exec="$ECLIPSE_BIN/eclipse" 
TargetEnvironment=Unity 

[RepositoryBrowser Shortcut Group] 
Name=Open the Repository Browser 
Exec="$ECLIPSE_BIN/eclipse" --repository-browser 
TargetEnvironment=Unity 
EOF 

# seems necessary to refresh immediately: 
chmod 644 $DESKTOP_FILE 

xdg-desktop-menu install $DESKTOP_FILE 
xdg-icon-resource install --size 32 --novendor "$ECLIPSE_BIN/icon.xpm" $ICON_NAME 
xdg-icon-resource install --size 48 --novendor "$ECLIPSE_BIN/icon.xpm" $ICON_NAME 
xdg-icon-resource install --size 64 --novendor "$ECLIPSE_BIN/icon.xpm" $ICON_NAME 
xdg-icon-resource install --size 128 --novendor "$ECLIPSE_BIN/icon.xpm" $ICON_NAME 

rm $DESKTOP_FILE 
rm -R $TMP_DIR
