#!/usr/bin/python3
#函数的本质是赋值运算
#为什么需要接口函数？
#code 层级调用是通过接口函数，接口函数从调用出生效 传值
#最后自查调用是否生效,一定要充分验证所有情况，比如bool有三种情况，yes no 不写
#例 https://github.com/avocado-framework/avocado-vt/pull/2893

qdevices ----> qcontainer(向外暴露接口函数) ----> tp-qemu cfg

def __init__(self, aobject, binary, sock_path, source, extra_options=None,
                 enable_debug_mode=False):
    super(QVirtioFSDev, self).__init__('virtiofs', aobject=aobject,
                                           child_bus=QUnixSocketBus(sock_path, aobject))
    self.set_param('enable_debug_mode', enable_debug_mode) # 这里查看set_param 返回  =====> def set_param(self, option, value, option_type=None, dynamic=False):
    
=====================================================================  
def set_param(self, option, value, option_type=None, dynamic=False):
    if dynamic:
        if option not in self.dynamic_params:
            self.dynamic_params.append(option)
    else:
        if option in self.dynamic_params:
            self.dynamic_params.remove(option)

    if option_type is bool or isinstance(value, bool):   ====================> #(enable_debug_mode 我们在上面写的预期是bool 类型=False，所有在此生效)
        if value in ['yes', 'on', True]:
            self.params[option] = "on"
        elif value in ['no', 'off', False]:              ====================> #（返回值为"off") 
            self.params[option] = "off"

=====================================================================  
#知道了enable_debug_mode 默认返回值为"off"后， 当我们从底层获取什么时发生改变？
#定义== "on"时
    def start_daemon(self):
        if self.get_param('enable_debug_mode') == "on":
            fsd_cmd += ' -d'
=====================================================================
这里 == "on" 不是直接从底层获取，注意层级关系，设置下层'qcontainer.py'接口函数
enable_debug_mode = params.get('fs_enable_debug_mode', 'no')  ====================> #（这里定义了对底层的获取接口名称'fs_enable_debug_mode'，并给定默认值) 

   def fs_define_by_params(self, name, params, bus=None):
        devices = []
        enable_debug_mode = params.get('fs_enable_debug_mode', 'no') == "yes"  ====================> #（这里设定成符合上层的bool类型，并且只有底层 == "yes" 时才为True
                    sock_path = os.path.join(data_dir.get_tmp_dir(),
                                             '-'.join((self.vmname, name, 'virtiofsd.sock')))
                    vfsd = qdevices.QVirtioFSDev(name, binary, sock_path,
                                                 source, extra_options, enable_debug_mode) ====================> #（记得传给上层 qdevices）
                    devices.append(vfsd)
    
    

def get_qdev_by_drive(self, device):
    """
    Get the qdev ID of device by drive name.  内容
    
    :param device: device name
    :type device: str
    :return: the qdev ID
    :rtype: str
    """
    for dev in self.__devices:
        try:
            if isinstance(dev, qdevices.QDevice) and device == dev.params['drive']:
                return dev.params['id']
        except KeyError:
            continue

#函数范例1：
def zzy(a, b):
    print(f"you have {a}")
    print(f"you have {b}")
    print("get a blanket.\n")

1:
zzy(20, 30)

2:
a = 10
b = 20

zzy(a, b)

3:
zzy(10 + 20, 5 + 6)

4:
zzy(a + 100, b + 1000)

--------------------------------------------------------------------------------------------------------------
#函数范例2：
#使用函数读取文件
from sys import argv

script, input_file = argv

def zzy1(f):         #将文件标记为只读
    print(f.read())

def zzy2(f):         #将读写跳到开头
    f.seek(0)

def zzy3(a, f):      #设定读取文件当前行！！！
    print(a, f.readline())

BL1 = open(input_file)  #定义变量1，把input_file标记为文件

print("First let's print the whole file:\n")
zzy1(BL1)

print("Now let's rewind, kind of like a tape.")
zzy2(BL1)

print("Let's print three lines:")
BL2 = 1             #变量BL2可以一直改变
zzy3(BL2, BL1)

BL2 = BL2 + 1
zzy3(BL2, BL1)

BL2 = BL2 + 1
zzy3(BL2, BL1)

--------------------------------------------------------------------------------------------------------------
#函数范例3：
#函数main中调用main，循环用if终止
import sys
script, encoding, error = sys.argv  #定义系统参数脚本，编码，错误


def main(language_file, encoding, errors):     #函数main3个参数
    line = language_file.readline()             #变量line 读当前行

    if line:                                    #检验变量line的真值，有内容即为真，否则跳过
        print_line(line, encoding, errors)       #调用函数print_line打印
        return main(language_file, encoding, errors) #循环执行main 直到这一行没有内容了


def print_line(line, encoding, errors):                      #函数print_line3个参数读当前行，编码，错误
    next_lang = line.strip()                                   #把每行结尾的\n删掉，字符串1
    raw_bytes = next_lang.encode(encoding, errors = errors)    # 使用.encode来编码字符串，变成原始字符串
    cooked_string = raw_bytes.decode(encoding, errors = errors)  #使用.decode将原始字符串变成，字符串1

    print(raw_bytes, "<===>", cooked_string)                   #原始字符串，根据原始字符串转换的 字符串1


languages = open("languages.txt", encoding = "utf-8")    #定义变量 打开languages.txt,指定编码格式为utf-8

main(languages, encoding, error)

--------------------------------------------------------------------------------------------------------------
#函数范例4：
#定义新变量存放函数返回值
def HS1(started):                                        #这个函数有一个参数
    a = started * 500                                    #之后对这一个参数做改变
    b = a / 1000
    c = b / 100
    return a, b, c                                       #函数返回值

HS1_BL = 10000                                           #函数中的参数
beans, b, c = HS1(HS1_BL)                                #定义新变量存放函数返回值

# remember that this is another way to format a string
print("With a starting point of: {}".format(HS1_BL))     #调用变量
print(f"With a starting point of: {HS1_BL}")
# it's just like with an f"" string
print(f"We'd have {beans} beans, {b} b, and {c} c.")

HS1_BL = HS1_BL / 10                                     #定义变量

print("We can also do that this way:")
formula = HS1(HS1_BL)                                    #定义变量formula =函数
# this is an easy way to apply a list to a format string      
print("We'd have {} beans, {} b, and {} c.".format(*formula)) #通用格式化formula

--------------------------------------------------------------------------------------------------------------
#函数范例5：
#split() 分割符用法
def break_words(stuff):
    """this function will break up words for us."""      #在python解释器中用的
    words1 = stuff.split(' ')
    words2 = stuff.split(' ', 2 )                        # 以空格为分隔符，分隔次数为2
    return words1, words2

stuff = """1 2 3 4 5"""
words1, words2 = break_words(stuff)
print(f"{words1}")
print(f"{words2}")

--------------------------------------------------------------------------------------------------------------
#添加进程锁
import time
import threading

lock = threading.Lock()  # 创建互斥锁
counter = 0  # 计数器


def counter_lock():
    global counter
    if lock.acquire():  # 请求互斥锁，如果被占用，则阻塞，直至获取到锁
        time.sleep(0.2)  # 假装思考、敲键盘需要0.2秒钟
        counter += 1
        print('我是第%d个' % counter)

    lock.release()  # 千万不要忘记释放互斥锁，否则后果很严重


def demo():
    threads = list()
    for i in range(3):  # 假设群里有3人，都喜欢吃苹果
        threads.append(threading.Thread(target=counter_lock))
        threads[-1].start()

    for t in threads:
        t.join()

    print('统计完毕，共有%d人' % counter)


if __name__ == '__main__':
    demo()

----------------------------------------------------------------------------------------------------------
1. 写一个函数传参打印30次，每次间隔0.1秒
import time

def slow_print(count='',n=30,delay=0.1):
    for i in range(n):                       
        print(count, end='', flush=True)
        time.sleep(delay)
        
slow_print('h ')
h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h

2.函数传参，传入一个参数列表
def square(x):
    return x ** 2
map(square, [1,2,3,4,5])
<map object at 0x7fdaa450a8d0>
[_ for _ in map(square, [1,2,3,4,5])]
[1, 4, 9, 16, 25]
