#!/usr/bin/python3
#-*-coding:utf-8-*-
#1.迭代器协议：对象需要提供next方法，要么返回迭代下一项，要么引起一个Stopteration异常，终止迭代。
#2.可迭代对象：实现迭代协议的对象
#3.可迭代对象实现迭代协议，Python的内置工具（for循环，sum，min，max等函数）使用迭代器访问对象
with open('/etc/passwd') as f: #文件对象提供迭代器协议
    for line in f:             #for循环使用迭代器协议访问文件
        print line
#2.生成器
#Python 使用生成器对延迟操作提供支持，所谓延迟操作，是指在需要的时候产生结果，而不是立即产生结果。
#Python有两种不同方式提供生成器：
#1.生成器函数：使用yield语句而不是return返回结果。
#2.生成器表达式：类似列表推导，生成器按需返回结果的一个对象，结果看着像列表（少了创建的过程）
def gensquares(N):
    for i in range(N):
        yield i ** 2          #生成自然数的平方，无需创建并添加至列表
                              #生成器自动返回对象，
for item in gensquares(5):
    print item,
