#!/usr/bin/python3
#-*-coding:utf-8-*-
#1.迭代器协议：对象需要提供next方法，要么返回迭代下一项，要么引起一个Stopteration异常，终止迭代。
#2.可迭代对象：实现迭代协议的对象
#3.可迭代对象实现迭代协议，Python的内置工具（for循环，sum，min，max等函数）使用迭代器访问对象
with open('/etc/passwd') as f: #文件对象提供迭代器协议
    for line in f:             #for循环使用迭代器协议访问文件
        print line
